-file("c:/erlang/erl9.1/lib/parsetools-2.1.5/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(xq_regex_scanner).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 147).

-file("c:/erlang/erl9.1/lib/parsetools-2.1.5/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/git/zadean/xqerl/src/xq_regex_scanner.erl", 303).
yystate() -> 62.

yystate(65, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(63, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(62, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line+1, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 35 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 37, C =< 39 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 47, C =< 62 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 64, C =< 90 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 95, C =< 122 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 126 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(62, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,62};
yystate(61, [90|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(59, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,59};
yystate(58, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(57, [123|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 32, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line,57};
yystate(56, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(55, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 99, C =< 102 ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(53, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line};
yystate(52, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(51, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, [44|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 19, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(46, Ics, Line, Tlen+1, 19, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,50};
yystate(49, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(49, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,49};
yystate(48, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(47, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(46, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(46, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(46, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,46};
yystate(45, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(44, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(43, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,43};
yystate(42, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(41, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(39, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(37, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,37};
yystate(36, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(33, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(33, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,33};
yystate(32, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(31, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,30};
yystate(29, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [91|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 12, Tlen);
yystate(28, [45|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 12, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,28};
yystate(27, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(26, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(25, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(23, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(19, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,19};
yystate(18, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(17, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Tlen, Action, Alen) when C >= 99, C =< 102 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,17};
yystate(16, [58|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 18, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,16};
yystate(15, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(14, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(13, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Tlen+1, 4, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,11};
yystate(10, [119|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [117|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [118|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [116|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [115|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [114|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [113|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [112|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [111|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [110|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [105|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [99|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [100|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [87|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [83|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [81|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [82|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [80|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [73|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [67|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [68|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [63|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [47|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [48|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [45|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [46|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [44|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [36|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [10|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 35 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 37, C =< 39 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 43 ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(11, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 62 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 66 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 72 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 79 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 86 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 88, C =< 90 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 98 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 104 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 109 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 120, C =< 122 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 125 ->
    yystate(7, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 126 ->
    yystate(3, Ics, Line, Tlen+1, 26, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,10};
yystate(9, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(7, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(6, [123|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 32, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line,6};
yystate(5, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(4, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,4};
yystate(3, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(2, [90|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,2};
yystate(1, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, [94|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 13, Tlen);
yystate(0, [45|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 13, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(29, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 101).
yyaction_0(TokenChars, TokenLine) ->
     { token, { 'CatEsc', TokenLine, TokenChars } } .

-compile({inline,yyaction_1/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 102).
yyaction_1(TokenChars, TokenLine) ->
     { token, { 'CatEsc', TokenLine, TokenChars } } .

-compile({inline,yyaction_2/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 103).
yyaction_2(TokenChars, TokenLine) ->
     { token, { 'ComplEsc', TokenLine, TokenChars } } .

-compile({inline,yyaction_3/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 104).
yyaction_3(TokenChars, TokenLine) ->
     { token, { 'ComplEsc', TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 106).
yyaction_4(TokenChars, TokenLine) ->
     { token, { 'BackReference', TokenLine, TokenChars } } .

-compile({inline,yyaction_5/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 108).
yyaction_5(TokenLine) ->
     { token, { sub, TokenLine, sub }, "[" } .

-compile({inline,yyaction_6/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 109).
yyaction_6(TokenLine) ->
     { token, { '[', TokenLine, '[' }, "\\-" } .

-compile({inline,yyaction_7/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 110).
yyaction_7(TokenLine) ->
     { token, { '[', TokenLine, '[' }, "^\\-" } .

-compile({inline,yyaction_8/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 111).
yyaction_8(TokenLine) ->
     { token, { 'NormalChar', TokenLine, "-" }, "-]" } .

-compile({inline,yyaction_9/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 113).
yyaction_9(TokenLine) ->
     { token, { '?:', TokenLine, '?:' } } .

-compile({inline,yyaction_10/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 114).
yyaction_10(TokenLine) ->
     { token, { '^', TokenLine, '^' } } .

-compile({inline,yyaction_11/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 115).
yyaction_11(TokenLine) ->
     { token, { '|', TokenLine, '|' } } .

-compile({inline,yyaction_12/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 116).
yyaction_12(TokenLine) ->
     { token, { '-', TokenLine, '-' } } .

-compile({inline,yyaction_13/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 117).
yyaction_13(TokenLine) ->
     { token, { '[', TokenLine, '[' } } .

-compile({inline,yyaction_14/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 118).
yyaction_14(TokenLine) ->
     { token, { ']', TokenLine, ']' } } .

-compile({inline,yyaction_15/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 119).
yyaction_15(TokenLine) ->
     { token, { '(', TokenLine, '(' } } .

-compile({inline,yyaction_16/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 120).
yyaction_16(TokenLine) ->
     { token, { ')', TokenLine, ')' } } .

-compile({inline,yyaction_17/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 121).
yyaction_17(TokenLine) ->
     { token, { '$', TokenLine, '$' } } .

-compile({inline,yyaction_18/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 123).
yyaction_18(TokenLine) ->
     { token, { '?', TokenLine, '?' } } .

-compile({inline,yyaction_19/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 124).
yyaction_19(TokenLine) ->
     { token, { '{', TokenLine, '{' } } .

-compile({inline,yyaction_20/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 125).
yyaction_20(TokenLine) ->
     { token, { '}', TokenLine, '}' } } .

-compile({inline,yyaction_21/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 126).
yyaction_21(TokenLine) ->
     { token, { '+', TokenLine, '+' } } .

-compile({inline,yyaction_22/1}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 127).
yyaction_22(TokenLine) ->
     { token, { '*', TokenLine, '*' } } .

-compile({inline,yyaction_23/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 130).
yyaction_23(TokenChars, TokenLine) ->
     { token, { 'QuantRange', TokenLine, TokenChars } } .

-compile({inline,yyaction_24/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 131).
yyaction_24(TokenChars, TokenLine) ->
     { token, { 'QuantMin', TokenLine, TokenChars } } .

-compile({inline,yyaction_25/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 132).
yyaction_25(TokenChars, TokenLine) ->
     { token, { 'QuantExact', TokenLine, TokenChars } } .

-compile({inline,yyaction_26/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 134).
yyaction_26(TokenChars, TokenLine) ->
     { token, { 'NormalChar', TokenLine, TokenChars } } .

-compile({inline,yyaction_27/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 136).
yyaction_27(TokenChars, TokenLine) ->
     { token, { 'WildcardEsc', TokenLine, TokenChars } } .

-compile({inline,yyaction_28/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 137).
yyaction_28(TokenChars, TokenLine) ->
     { token, { 'SingleCharNoEsc', TokenLine, TokenChars } } .

-compile({inline,yyaction_29/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 138).
yyaction_29(TokenChars, TokenLine) ->
     { token, { 'SingleCharEsc', TokenLine, TokenChars } } .

-compile({inline,yyaction_30/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 140).
yyaction_30(TokenChars, TokenLine) ->
     { token, { 'MultiCharEsc', TokenLine, TokenChars } } .

-compile({inline,yyaction_31/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 141).
yyaction_31(TokenChars, TokenLine) ->
     { token, { 'MultiCharComplEsc', TokenLine, TokenChars } } .

-compile({inline,yyaction_32/2}).
-file("/git/zadean/xqerl/src/xq_regex_scanner.xrl", 143).
yyaction_32(TokenChars, TokenLine) ->
     { token, { 'BadCharEsc', TokenLine, TokenChars } } .

-file("c:/erlang/erl9.1/lib/parsetools-2.1.5/include/leexinc.hrl", 309).
