%% @author Zack
%% @doc @todo Add description to xqerl_try.
-module(xqerl_try).
-include("xqerl.hrl").




-export([main/1]).

-variables([]).

-functions([{{qname, "http://www.w3.org/2005/xquery-local-functions", "local",
         "f"},
        {xqSeqType,
         {xqFunTest, function, [], undefined,
          [{xqSeqType, {xqKindTest, namespace, undefined, undefined, undefined}, one}],
          {xqSeqType, element, one}},
         one},
        [], {'fx$^4', 2}, 1,
        [{xqSeqType, {xqKindTest, namespace, undefined, undefined, undefined}, one}]}]).

-export([]).

init() ->
    xqerl_context:init(),
    #{'base-uri' => {xqAtomicValue, 'xs:anyURI', "http://xqerl.org"},
      'construction-mode' => preserve,
      'copy-namespaces' => {'no-preserve', 'no-inherit'},
      'default-collation' =>
     "http://www.w3.org/2005/xpath-functions/collation/codepoint",
      known_collations =>
     ["http://www.w3.org/2005/xpath-functions/collation/codepoint"],
      named_functions =>
     [{{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "append"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, append, 3}, 2,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "filter"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, filter, 3}, 2,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType,
         {xqFunTest, function, [], undefined, [{xqSeqType, item, zero_or_many}],
          {xqSeqType, 'xs:boolean', one}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "flatten"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_array, flatten, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "fold-left"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_array, 'fold-left', 4}, 3,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, item, zero_or_many},
        {xqSeqType,
         {xqFunTest, function, [], undefined,
          [{xqSeqType, item, zero_or_many}, {xqSeqType, item, zero_or_many}],
          {xqSeqType, item, zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "fold-right"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_array, 'fold-right', 4}, 3,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, item, zero_or_many},
        {xqSeqType,
         {xqFunTest, function, [], undefined,
          [{xqSeqType, item, zero_or_many}, {xqSeqType, item, zero_or_many}],
          {xqSeqType, item, zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "for-each"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, 'for-each', 3}, 2,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType,
         {xqFunTest, function, [], undefined, [{xqSeqType, item, zero_or_many}],
          {xqSeqType, item, zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array",
        "for-each-pair"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, 'for-each-pair', 4}, 3,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType,
         {xqFunTest, function, [], undefined,
          [{xqSeqType, item, zero_or_many}, {xqSeqType, item, zero_or_many}],
          {xqSeqType, item, zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "get"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_array, get, 3}, 2,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, 'xs:integer', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "head"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_array, head, 2}, 1,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array",
        "insert-before"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, 'insert-before', 4}, 3,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, 'xs:integer', one}, {xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "join"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, join, 2}, 1,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "put"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, put, 4}, 3,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, 'xs:integer', one}, {xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "remove"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, remove, 3}, 2,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, 'xs:integer', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "reverse"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, reverse, 2}, 1,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "size"},
       {xqSeqType, 'xs:integer', one}, [], {xqerl_array, size, 2}, 1,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "sort"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, sort, 2}, 1,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "sort"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, sort, 3}, 2,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "sort"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, sort, 4}, 3,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType,
         {xqFunTest, function, [], undefined, [{xqSeqType, item, zero_or_many}],
          {xqSeqType, 'xs:anyAtomicType', zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "subarray"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, subarray, 3}, 2,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, 'xs:integer', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "subarray"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, subarray, 4}, 3,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one},
        {xqSeqType, 'xs:integer', one}, {xqSeqType, 'xs:integer', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/array", "array", "tail"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_array, tail, 2}, 1,
       [{xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "contains"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_map, contains, 3}, 2,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, one},
        {xqSeqType, 'xs:anyAtomicType', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "entry"},
       {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}, [],
       {xqerl_map, entry, 3}, 2,
       [{xqSeqType, 'xs:anyAtomicType', one}, {xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "find"},
       {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}, [],
       {xqerl_map, find, 3}, 2,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, 'xs:anyAtomicType', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "for-each"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_map, 'for-each', 3}, 2,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, one},
        {xqSeqType,
         {xqFunTest, function, [], undefined,
          [{xqSeqType, 'xs:anyAtomicType', one}, {xqSeqType, item, zero_or_many}],
          {xqSeqType, item, zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "get"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_map, get, 3}, 2,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, one},
        {xqSeqType, 'xs:anyAtomicType', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "keys"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_many}, [], {xqerl_map, keys, 2}, 1,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "merge"},
       {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}, [],
       {xqerl_map, merge, 2}, 1,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "merge"},
       {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}, [],
       {xqerl_map, merge, 3}, 2,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, zero_or_many},
        {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "put"},
       {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}, [],
       {xqerl_map, put, 4}, 3,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, one},
        {xqSeqType, 'xs:anyAtomicType', one}, {xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "remove"},
       {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}, [],
       {xqerl_map, remove, 3}, 2,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, one},
        {xqSeqType, 'xs:anyAtomicType', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/map", "map", "size"},
       {xqSeqType, 'xs:integer', one}, [], {xqerl_map, size, 2}, 1,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "acos"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, acos, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "asin"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, asin, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "atan"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, atan, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "atan2"},
       {xqSeqType, 'xs:double', one}, [], {xqerl_math, atan2, 3}, 2,
       [{xqSeqType, 'xs:double', one}, {xqSeqType, 'xs:double', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "cos"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, cos, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "exp"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, exp, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "exp10"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, exp10, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "log"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, log, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "log10"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, log10, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "pi"},
       {xqSeqType, 'xs:double', one}, [], {xqerl_math, pi, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "pow"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, pow, 3}, 2,
       [{xqSeqType, 'xs:double', zero_or_one}, {xqSeqType, 'xs:numeric', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "sin"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, sin, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "sqrt"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, sqrt, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions/math", "math", "tan"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_math, tan, 2}, 1,
       [{xqSeqType, 'xs:double', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "unsignedInt"},
       {xqSeqType, 'xs:unsignedInt', zero_or_one}, [], {xqerl_xs, xs_unsignedInt, 2},
       1, [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "string"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_xs, xs_string, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "boolean"},
       {xqSeqType, 'xs:boolean', zero_or_one}, [], {xqerl_xs, xs_boolean, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "decimal"},
       {xqSeqType, 'xs:decimal', zero_or_one}, [], {xqerl_xs, xs_decimal, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "float"},
       {xqSeqType, 'xs:float', zero_or_one}, [], {xqerl_xs, xs_float, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "double"},
       {xqSeqType, 'xs:double', zero_or_one}, [], {xqerl_xs, xs_double, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "duration"},
       {xqSeqType, 'xs:duration', zero_or_one}, [], {xqerl_xs, xs_duration, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "dateTime"},
       {xqSeqType, 'xs:dateTime', zero_or_one}, [], {xqerl_xs, xs_dateTime, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "time"},
       {xqSeqType, 'xs:time', zero_or_one}, [], {xqerl_xs, xs_time, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "date"},
       {xqSeqType, 'xs:date', zero_or_one}, [], {xqerl_xs, xs_date, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "gYearMonth"},
       {xqSeqType, 'xs:gYearMonth', zero_or_one}, [], {xqerl_xs, xs_gYearMonth, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "gYear"},
       {xqSeqType, 'xs:gYear', zero_or_one}, [], {xqerl_xs, xs_gYear, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "gMonthDay"},
       {xqSeqType, 'xs:gMonthDay', zero_or_one}, [], {xqerl_xs, xs_gMonthDay, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "gDay"},
       {xqSeqType, 'xs:gDay', zero_or_one}, [], {xqerl_xs, xs_gDay, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "gMonth"},
       {xqSeqType, 'xs:gMonth', zero_or_one}, [], {xqerl_xs, xs_gMonth, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "hexBinary"},
       {xqSeqType, 'xs:hexBinary', zero_or_one}, [], {xqerl_xs, xs_hexBinary, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "base64Binary"},
       {xqSeqType, 'xs:base64Binary', zero_or_one}, [], {xqerl_xs, xs_base64Binary, 2},
       1, [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "anyURI"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [], {xqerl_xs, xs_anyURI, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "QName"},
       {xqSeqType, 'xs:QName', zero_or_one}, [], {xqerl_xs, xs_QName, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "normalizedString"},
       {xqSeqType, 'xs:normalizedString', zero_or_one}, [],
       {xqerl_xs, xs_normalizedString, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "token"},
       {xqSeqType, 'xs:token', zero_or_one}, [], {xqerl_xs, xs_token, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "language"},
       {xqSeqType, 'xs:language', zero_or_one}, [], {xqerl_xs, xs_language, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "NMTOKEN"},
       {xqSeqType, 'xs:NMTOKEN', zero_or_one}, [], {xqerl_xs, xs_NMTOKEN, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "Name"},
       {xqSeqType, 'xs:Name', zero_or_one}, [], {xqerl_xs, xs_Name, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "NCName"},
       {xqSeqType, 'xs:NCName', zero_or_one}, [], {xqerl_xs, xs_NCName, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "ID"},
       {xqSeqType, 'xs:ID', zero_or_one}, [], {xqerl_xs, xs_ID, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "IDREF"},
       {xqSeqType, 'xs:IDREF', zero_or_one}, [], {xqerl_xs, xs_IDREF, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "ENTITY"},
       {xqSeqType, 'xs:ENTITY', zero_or_one}, [], {xqerl_xs, xs_ENTITY, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "integer"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_xs, xs_integer, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "nonPositiveInteger"},
       {xqSeqType, 'xs:nonPositiveInteger', zero_or_one}, [],
       {xqerl_xs, xs_nonPositiveInteger, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "negativeInteger"},
       {xqSeqType, 'xs:negativeInteger', zero_or_one}, [],
       {xqerl_xs, xs_negativeInteger, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "long"},
       {xqSeqType, 'xs:long', zero_or_one}, [], {xqerl_xs, xs_long, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "int"},
       {xqSeqType, 'xs:int', zero_or_one}, [], {xqerl_xs, xs_int, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "short"},
       {xqSeqType, 'xs:short', zero_or_one}, [], {xqerl_xs, xs_short, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "byte"},
       {xqSeqType, 'xs:byte', zero_or_one}, [], {xqerl_xs, xs_byte, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "nonNegativeInteger"},
       {xqSeqType, 'xs:nonNegativeInteger', zero_or_one}, [],
       {xqerl_xs, xs_nonNegativeInteger, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "unsignedLong"},
       {xqSeqType, 'xs:unsignedLong', zero_or_one}, [], {xqerl_xs, xs_unsignedLong, 2},
       1, [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "unsignedShort"},
       {xqSeqType, 'xs:unsignedShort', zero_or_one}, [],
       {xqerl_xs, xs_unsignedShort, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "unsignedByte"},
       {xqSeqType, 'xs:unsignedByte', zero_or_one}, [], {xqerl_xs, xs_unsignedByte, 2},
       1, [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "positiveInteger"},
       {xqSeqType, 'xs:positiveInteger', zero_or_one}, [],
       {xqerl_xs, xs_positiveInteger, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "yearMonthDuration"},
       {xqSeqType, 'xs:yearMonthDuration', zero_or_one}, [],
       {xqerl_xs, xs_yearMonthDuration, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "dayTimeDuration"},
       {xqSeqType, 'xs:dayTimeDuration', zero_or_one}, [],
       {xqerl_xs, xs_dayTimeDuration, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "untypedAtomic"},
       {xqSeqType, 'xs:untypedAtomic', zero_or_one}, [],
       {xqerl_xs, xs_untypedAtomic, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "dateTimeStamp"},
       {xqSeqType, 'xs:dateTimeStamp', zero_or_one}, [],
       {xqerl_xs, xs_dateTimeStamp, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "NMTOKENS"},
       {xqSeqType, 'xs:NMTOKENS', zero_or_one}, [], {xqerl_xs, xs_NMTOKENS, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "ENTITIES"},
       {xqSeqType, 'xs:ENTITIES', zero_or_one}, [], {xqerl_xs, xs_ENTITIES, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "IDREFS"},
       {xqSeqType, 'xs:IDREFS', zero_or_one}, [], {xqerl_xs, xs_IDREFS, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2001/XMLSchema", "xs", "error"},
       {xqSeqType, 'xs:error', zero_or_one}, [], {xqerl_xs, xs_error, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "abs"},
       {xqSeqType, 'xs:numeric', zero_or_one}, [], {xqerl_fn, abs, 2}, 1,
       [{xqSeqType, 'xs:numeric', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "adjust-dateTime-to-timezone"},
       {xqSeqType, 'xs:dateTime', zero_or_one}, [],
       {xqerl_fn, 'adjust-dateTime-to-timezone', 2}, 1,
       [{xqSeqType, 'xs:dateTime', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "adjust-dateTime-to-timezone"},
       {xqSeqType, 'xs:dateTime', zero_or_one}, [],
       {xqerl_fn, 'adjust-dateTime-to-timezone', 3}, 2,
       [{xqSeqType, 'xs:dateTime', zero_or_one},
        {xqSeqType, 'xs:dayTimeDuration', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "adjust-date-to-timezone"},
       {xqSeqType, 'xs:date', zero_or_one}, [],
       {xqerl_fn, 'adjust-date-to-timezone', 2}, 1,
       [{xqSeqType, 'xs:date', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "adjust-date-to-timezone"},
       {xqSeqType, 'xs:date', zero_or_one}, [],
       {xqerl_fn, 'adjust-date-to-timezone', 3}, 2,
       [{xqSeqType, 'xs:date', zero_or_one},
        {xqSeqType, 'xs:dayTimeDuration', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "adjust-time-to-timezone"},
       {xqSeqType, 'xs:time', zero_or_one}, [],
       {xqerl_fn, 'adjust-time-to-timezone', 2}, 1,
       [{xqSeqType, 'xs:time', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "adjust-time-to-timezone"},
       {xqSeqType, 'xs:time', zero_or_one}, [],
       {xqerl_fn, 'adjust-time-to-timezone', 3}, 2,
       [{xqSeqType, 'xs:time', zero_or_one},
        {xqSeqType, 'xs:dayTimeDuration', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "analyze-string"},
       {xqSeqType, {xqKindTest, element, undefined, undefined, undefined}, one}, [],
       {xqerl_fn, 'analyze-string', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "analyze-string"},
       {xqSeqType, {xqKindTest, element, undefined, undefined, undefined}, one}, [],
       {xqerl_fn, 'analyze-string', 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "apply"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, apply, 3}, 2,
       [{xqSeqType, {xqFunTest, function, [], undefined, any, any}, one},
        {xqSeqType, {xqFunTest, array, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "available-environment-variables"},
       {xqSeqType, 'xs:string', zero_or_many}, [],
       {xqerl_fn, 'available-environment-variables', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "avg"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_one}, [], {xqerl_fn, avg, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "base-uri"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [], {xqerl_fn, 'base-uri', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "base-uri"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [], {xqerl_fn, 'base-uri', 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "boolean"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, boolean, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "ceiling"},
       {xqSeqType, 'xs:numeric', zero_or_one}, [], {xqerl_fn, ceiling, 2}, 1,
       [{xqSeqType, 'xs:numeric', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "codepoint-equal"},
       {xqSeqType, 'xs:boolean', zero_or_one}, [], {xqerl_fn, 'codepoint-equal', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "codepoints-to-string"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'codepoints-to-string', 2}, 1,
       [{xqSeqType, 'xs:integer', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "collation-key"},
       {xqSeqType, 'xs:base64Binary', one}, [], {xqerl_fn, 'collation-key', 2}, 1,
       [{xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "collation-key"},
       {xqSeqType, 'xs:base64Binary', one}, [], {xqerl_fn, 'collation-key', 3}, 2,
       [{xqSeqType, 'xs:string', one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "collection"},
       {xqSeqType, item, one}, [], {xqerl_fn, collection, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "collection"},
       {xqSeqType, item, one}, [], {xqerl_fn, collection, 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "compare"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, compare, 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "compare"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, compare, 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "concat"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, concat, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "contains"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, contains, 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "contains"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, contains, 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "contains-token"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'contains-token', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_many}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "contains-token"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'contains-token', 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_many}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "count"},
       {xqSeqType, 'xs:integer', one}, [], {xqerl_fn, count, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "current-date"},
       {xqSeqType, 'xs:date', one}, [], {xqerl_fn, 'current-date', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "current-dateTime"},
       {xqSeqType, 'xs:dateTime', one}, [], {xqerl_fn, 'current-dateTime', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "current-time"},
       {xqSeqType, 'xs:time', one}, [], {xqerl_fn, 'current-time', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "data"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_many}, [], {xqerl_fn, data, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "data"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_many}, [], {xqerl_fn, data, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "dateTime"},
       {xqSeqType, 'xs:dateTime', zero_or_one}, [], {xqerl_fn, dateTime, 3}, 2,
       [{xqSeqType, 'xs:date', zero_or_one}, {xqSeqType, 'xs:time', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "day-from-date"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, 'day-from-date', 2}, 1,
       [{xqSeqType, 'xs:date', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "day-from-dateTime"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, 'day-from-dateTime', 2},
       1, [{xqSeqType, 'xs:dateTime', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "days-from-duration"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, 'days-from-duration', 2},
       1, [{xqSeqType, 'xs:duration', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "deep-equal"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'deep-equal', 3}, 2,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "deep-equal"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'deep-equal', 4}, 3,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, item, zero_or_many},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "default-collation"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'default-collation', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "default-language"},
       {xqSeqType, 'xs:language', one}, [], {xqerl_fn, 'default-language', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "distinct-values"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_many}, [],
       {xqerl_fn, 'distinct-values', 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "distinct-values"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_many}, [],
       {xqerl_fn, 'distinct-values', 3}, 2,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "doc"},
       {xqSeqType, {xqKindTest, 'document-node', undefined, undefined, undefined},
        zero_or_one},
       [], {xqerl_fn, doc, 2}, 1, [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "doc-available"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'doc-available', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "document-uri"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [], {xqerl_fn, 'document-uri', 1}, 0,
       []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "document-uri"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [], {xqerl_fn, 'document-uri', 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "element-with-id"},
       {xqSeqType, {xqKindTest, element, undefined, undefined, undefined},
        zero_or_many},
       [], {xqerl_fn, 'element-with-id', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "element-with-id"},
       {xqSeqType, {xqKindTest, element, undefined, undefined, undefined},
        zero_or_many},
       [], {xqerl_fn, 'element-with-id', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_many},
        {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "empty"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, empty, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "encode-for-uri"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'encode-for-uri', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "ends-with"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'ends-with', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "ends-with"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'ends-with', 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "environment-variable"},
       {xqSeqType, 'xs:string', zero_or_one}, [],
       {xqerl_fn, 'environment-variable', 2}, 1, [{xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "error"},
       {xqSeqType, 'empty-sequence', none}, [], {xqerl_fn, error, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "error"},
       {xqSeqType, 'empty-sequence', none}, [], {xqerl_fn, error, 2}, 1,
       [{xqSeqType, 'xs:QName', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "error"},
       {xqSeqType, 'empty-sequence', none}, [], {xqerl_fn, error, 3}, 2,
       [{xqSeqType, 'xs:QName', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "error"},
       {xqSeqType, 'empty-sequence', none}, [], {xqerl_fn, error, 4}, 3,
       [{xqSeqType, 'xs:QName', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "escape-html-uri"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'escape-html-uri', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "exactly-one"},
       {xqSeqType, item, one}, [], {xqerl_fn, 'exactly-one', 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "exists"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, exists, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "false"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, false, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "filter"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, filter, 3}, 2,
       [{xqSeqType, item, zero_or_many},
        {xqSeqType,
         {xqFunTest, function, [],
          {qname, "http://www.w3.org/2005/xpath-functions", "fn", "filter"},
          [{xqSeqType, item, one}], {xqSeqType, 'xs:boolean', one}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "floor"},
       {xqSeqType, 'xs:numeric', zero_or_one}, [], {xqerl_fn, floor, 2}, 1,
       [{xqSeqType, 'xs:numeric', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "fold-left"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, 'fold-left', 4}, 3,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, item, zero_or_many},
        {xqSeqType,
         {xqFunTest, function, [],
          {qname, "http://www.w3.org/2005/xpath-functions", "fn", "fold-left"},
          [{xqSeqType, item, zero_or_many}, {xqSeqType, item, one}],
          {xqSeqType, item, zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "fold-right"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, 'fold-right', 4}, 3,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, item, zero_or_many},
        {xqSeqType,
         {xqFunTest, function, [],
          {qname, "http://www.w3.org/2005/xpath-functions", "fn", "fold-right"},
          [{xqSeqType, item, zero_or_many}, {xqSeqType, item, one}],
          {xqSeqType, item, zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "for-each"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, 'for-each', 3}, 2,
       [{xqSeqType, item, zero_or_many},
        {xqSeqType,
         {xqFunTest, function, [],
          {qname, "http://www.w3.org/2005/xpath-functions", "fn", "for-each"},
          [{xqSeqType, item, one}], {xqSeqType, item, zero_or_many}},
         zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "for-each-pair"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, 'for-each-pair', 4}, 3,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, item, zero_or_many},
        {xqSeqType,
         {xqFunTest, function, [],
          {qname, "http://www.w3.org/2005/xpath-functions", "fn", "for-each-pair"},
          [{xqSeqType, item, one}, {xqSeqType, item, one}],
          {xqSeqType, item, zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-date"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'format-date', 3}, 2,
       [{xqSeqType, 'xs:date', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-date"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'format-date', 6}, 5,
       [{xqSeqType, 'xs:date', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-dateTime"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'format-dateTime', 3}, 2,
       [{xqSeqType, 'xs:dateTime', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-dateTime"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'format-dateTime', 6}, 5,
       [{xqSeqType, 'xs:dateTime', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-integer"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'format-integer', 3}, 2,
       [{xqSeqType, 'xs:integer', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-integer"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'format-integer', 4}, 3,
       [{xqSeqType, 'xs:integer', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-number"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'format-number', 3}, 2,
       [{xqSeqType, 'xs:numeric', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-number"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'format-number', 4}, 3,
       [{xqSeqType, 'xs:numeric', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-time"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'format-time', 3}, 2,
       [{xqSeqType, 'xs:time', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "format-time"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'format-time', 6}, 5,
       [{xqSeqType, 'xs:time', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "function-arity"},
       {xqSeqType, 'xs:integer', one}, [], {xqerl_fn, 'function-arity', 2}, 1,
       [{xqSeqType, {xqFunTest, function, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "function-lookup"},
       {xqSeqType, {xqFunTest, function, [], undefined, any, any}, zero_or_one}, [],
       {xqerl_fn, 'function-lookup', 3}, 2,
       [{xqSeqType, 'xs:QName', one}, {xqSeqType, 'xs:integer', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "function-name"},
       {xqSeqType, 'xs:QName', zero_or_one}, [], {xqerl_fn, 'function-name', 2}, 1,
       [{xqSeqType, {xqFunTest, function, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "generate-id"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'generate-id', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "generate-id"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'generate-id', 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "has-children"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'has-children', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "has-children"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'has-children', 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "head"},
       {xqSeqType, item, zero_or_one}, [], {xqerl_fn, head, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "hours-from-dateTime"},
       {xqSeqType, 'xs:integer', zero_or_one}, [],
       {xqerl_fn, 'hours-from-dateTime', 2}, 1,
       [{xqSeqType, 'xs:dateTime', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "hours-from-duration"},
       {xqSeqType, 'xs:integer', zero_or_one}, [],
       {xqerl_fn, 'hours-from-duration', 2}, 1,
       [{xqSeqType, 'xs:duration', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "hours-from-time"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, 'hours-from-time', 2}, 1,
       [{xqSeqType, 'xs:time', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "id"},
       {xqSeqType, {xqKindTest, element, undefined, undefined, undefined},
        zero_or_many},
       [], {xqerl_fn, id, 2}, 1, [{xqSeqType, 'xs:string', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "id"},
       {xqSeqType, {xqKindTest, element, undefined, undefined, undefined},
        zero_or_many},
       [], {xqerl_fn, id, 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_many},
        {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "idref"},
       {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, zero_or_many},
       [], {xqerl_fn, idref, 2}, 1, [{xqSeqType, 'xs:string', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "idref"},
       {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, zero_or_many},
       [], {xqerl_fn, idref, 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_many},
        {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "implicit-timezone"},
       {xqSeqType, 'xs:dayTimeDuration', one}, [], {xqerl_fn, 'implicit-timezone', 1},
       0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "index-of"},
       {xqSeqType, 'xs:integer', zero_or_many}, [], {xqerl_fn, 'index-of', 3}, 2,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many},
        {xqSeqType, 'xs:anyAtomicType', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "index-of"},
       {xqSeqType, 'xs:integer', zero_or_many}, [], {xqerl_fn, 'index-of', 4}, 3,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many},
        {xqSeqType, 'xs:anyAtomicType', one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "innermost"},
       {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, zero_or_many},
       [], {xqerl_fn, innermost, 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "in-scope-prefixes"},
       {xqSeqType, 'xs:string', zero_or_many}, [], {xqerl_fn, 'in-scope-prefixes', 2},
       1, [{xqSeqType, {xqKindTest, element, undefined, undefined, undefined}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "insert-before"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, 'insert-before', 4}, 3,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, 'xs:integer', one},
        {xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "iri-to-uri"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'iri-to-uri', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "json-doc"},
       {xqSeqType, item, zero_or_one}, [], {xqerl_fn, 'json-doc', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "json-doc"},
       {xqSeqType, item, zero_or_one}, [], {xqerl_fn, 'json-doc', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "json-to-xml"},
       {xqSeqType, {xqKindTest, 'document-node', undefined, undefined, undefined},
        one},
       [], {xqerl_fn, 'json-to-xml', 2}, 1, [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "json-to-xml"},
       {xqSeqType, {xqKindTest, 'document-node', undefined, undefined, undefined},
        one},
       [], {xqerl_fn, 'json-to-xml', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "lang"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, lang, 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "lang"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, lang, 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "last"},
       {xqSeqType, 'xs:integer', one}, [], {xqerl_fn, last, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "load-xquery-module"},
       {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}, [],
       {xqerl_fn, 'load-xquery-module', 2}, 1, [{xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "load-xquery-module"},
       {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}, [],
       {xqerl_fn, 'load-xquery-module', 3}, 2,
       [{xqSeqType, 'xs:string', one},
        {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "local-name"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'local-name', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "local-name"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'local-name', 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "local-name-from-QName"},
       {xqSeqType, 'xs:NCName', zero_or_one}, [],
       {xqerl_fn, 'local-name-from-QName', 2}, 1,
       [{xqSeqType, 'xs:QName', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "lower-case"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'lower-case', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "matches"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, matches, 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "matches"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, matches, 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "max"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_one}, [], {xqerl_fn, max, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "max"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_one}, [], {xqerl_fn, max, 3}, 2,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "min"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_one}, [], {xqerl_fn, min, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "min"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_one}, [], {xqerl_fn, min, 3}, 2,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "minutes-from-dateTime"},
       {xqSeqType, 'xs:integer', zero_or_one}, [],
       {xqerl_fn, 'minutes-from-dateTime', 2}, 1,
       [{xqSeqType, 'xs:dateTime', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "minutes-from-duration"},
       {xqSeqType, 'xs:integer', zero_or_one}, [],
       {xqerl_fn, 'minutes-from-duration', 2}, 1,
       [{xqSeqType, 'xs:duration', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "minutes-from-time"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, 'minutes-from-time', 2},
       1, [{xqSeqType, 'xs:time', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "month-from-date"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, 'month-from-date', 2}, 1,
       [{xqSeqType, 'xs:date', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "month-from-dateTime"},
       {xqSeqType, 'xs:integer', zero_or_one}, [],
       {xqerl_fn, 'month-from-dateTime', 2}, 1,
       [{xqSeqType, 'xs:dateTime', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "months-from-duration"},
       {xqSeqType, 'xs:integer', zero_or_one}, [],
       {xqerl_fn, 'months-from-duration', 2}, 1,
       [{xqSeqType, 'xs:duration', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "name"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, name, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "name"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, name, 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "namespace-uri"},
       {xqSeqType, 'xs:anyURI', one}, [], {xqerl_fn, 'namespace-uri', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "namespace-uri"},
       {xqSeqType, 'xs:anyURI', one}, [], {xqerl_fn, 'namespace-uri', 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "namespace-uri-for-prefix"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [],
       {xqerl_fn, 'namespace-uri-for-prefix', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, {xqKindTest, element, undefined, undefined, undefined}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "namespace-uri-from-QName"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [],
       {xqerl_fn, 'namespace-uri-from-QName', 2}, 1,
       [{xqSeqType, 'xs:QName', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "nilled"},
       {xqSeqType, 'xs:boolean', zero_or_one}, [], {xqerl_fn, nilled, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "nilled"},
       {xqSeqType, 'xs:boolean', zero_or_one}, [], {xqerl_fn, nilled, 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "node-name"},
       {xqSeqType, 'xs:QName', zero_or_one}, [], {xqerl_fn, 'node-name', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "node-name"},
       {xqSeqType, 'xs:QName', zero_or_one}, [], {xqerl_fn, 'node-name', 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "normalize-space"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'normalize-space', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "normalize-space"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'normalize-space', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "normalize-unicode"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'normalize-unicode', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "normalize-unicode"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'normalize-unicode', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "not"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'not', 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "number"},
       {xqSeqType, 'xs:double', one}, [], {xqerl_fn, number, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "number"},
       {xqSeqType, 'xs:double', one}, [], {xqerl_fn, number, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "one-or-more"},
       {xqSeqType, item, one_or_many}, [], {xqerl_fn, 'one-or-more', 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "outermost"},
       {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, zero_or_many},
       [], {xqerl_fn, outermost, 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "parse-ietf-date"},
       {xqSeqType, 'xs:dateTime', zero_or_one}, [], {xqerl_fn, 'parse-ietf-date', 2},
       1, [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "parse-json"},
       {xqSeqType, item, zero_or_one}, [], {xqerl_fn, 'parse-json', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "parse-json"},
       {xqSeqType, item, zero_or_one}, [], {xqerl_fn, 'parse-json', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "parse-xml"},
       {xqSeqType,
        {is_document, {xqKindTest, element, undefined, undefined, undefined}}, one},
       [], {xqerl_fn, 'parse-xml', 2}, 1, [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "parse-xml-fragment"},
       {xqSeqType, {xqKindTest, 'document-node', undefined, undefined, undefined},
        zero_or_one},
       [], {xqerl_fn, 'parse-xml-fragment', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "path"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, path, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "path"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, path, 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "position"},
       {xqSeqType, 'xs:integer', one}, [], {xqerl_fn, position, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "prefix-from-QName"},
       {xqSeqType, 'xs:NCName', zero_or_one}, [], {xqerl_fn, 'prefix-from-QName', 2},
       1, [{xqSeqType, 'xs:QName', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "QName"},
       {xqSeqType, 'xs:QName', one}, [], {xqerl_fn, 'QName', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "random-number-generator"},
       {xqSeqType,
        {xqFunTest, map, [], undefined, [{xqSeqType, 'xs:string', one}],
         {xqSeqType, item, one}},
        one},
       [], {xqerl_fn, 'random-number-generator', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "random-number-generator"},
       {xqSeqType,
        {xqFunTest, map, [], undefined, [{xqSeqType, 'xs:string', one}],
         {xqSeqType, item, one}},
        one},
       [], {xqerl_fn, 'random-number-generator', 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "remove"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, remove, 3}, 2,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, 'xs:integer', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "replace"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, replace, 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "replace"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, replace, 5}, 4,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "resolve-QName"},
       {xqSeqType, 'xs:QName', zero_or_one}, [], {xqerl_fn, 'resolve-QName', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, {xqKindTest, element, undefined, undefined, undefined}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "resolve-uri"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [], {xqerl_fn, 'resolve-uri', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "resolve-uri"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [], {xqerl_fn, 'resolve-uri', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "reverse"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, reverse, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "root"},
       {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, one}, [],
       {xqerl_fn, root, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "root"},
       {xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, zero_or_one},
       [], {xqerl_fn, root, 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "round"},
       {xqSeqType, 'xs:numeric', zero_or_one}, [], {xqerl_fn, round, 2}, 1,
       [{xqSeqType, 'xs:numeric', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "round"},
       {xqSeqType, 'xs:numeric', zero_or_one}, [], {xqerl_fn, round, 3}, 2,
       [{xqSeqType, 'xs:numeric', zero_or_one}, {xqSeqType, 'xs:integer', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "round-half-to-even"},
       {xqSeqType, 'xs:numeric', zero_or_one}, [], {xqerl_fn, 'round-half-to-even', 2},
       1, [{xqSeqType, 'xs:numeric', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "round-half-to-even"},
       {xqSeqType, 'xs:numeric', zero_or_one}, [], {xqerl_fn, 'round-half-to-even', 3},
       2, [{xqSeqType, 'xs:numeric', zero_or_one}, {xqSeqType, 'xs:integer', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "seconds-from-dateTime"},
       {xqSeqType, 'xs:decimal', zero_or_one}, [],
       {xqerl_fn, 'seconds-from-dateTime', 2}, 1,
       [{xqSeqType, 'xs:dateTime', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "seconds-from-duration"},
       {xqSeqType, 'xs:decimal', zero_or_one}, [],
       {xqerl_fn, 'seconds-from-duration', 2}, 1,
       [{xqSeqType, 'xs:duration', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "seconds-from-time"},
       {xqSeqType, 'xs:decimal', zero_or_one}, [], {xqerl_fn, 'seconds-from-time', 2},
       1, [{xqSeqType, 'xs:time', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "serialize"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, serialize, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "serialize"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, serialize, 3}, 2,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, item, zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "sort"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, sort, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "sort"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, sort, 3}, 2,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "sort"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, sort, 4}, 3,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType,
         {xqFunTest, function, [],
          {qname, "http://www.w3.org/2005/xpath-functions", "fn", "sort"},
          [{xqSeqType, item, one}], {xqSeqType, 'xs:anyAtomicType', zero_or_many}},
         one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "starts-with"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'starts-with', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "starts-with"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'starts-with', 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "static-base-uri"},
       {xqSeqType, 'xs:anyURI', zero_or_one}, [], {xqerl_fn, 'static-base-uri', 1}, 0,
       []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "string"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, string, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "string"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, string, 2}, 1,
       [{xqSeqType, item, zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "string-join"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'string-join', 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "string-join"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'string-join', 3}, 2,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "string-length"},
       {xqSeqType, 'xs:integer', one}, [], {xqerl_fn, 'string-length', 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "string-length"},
       {xqSeqType, 'xs:integer', one}, [], {xqerl_fn, 'string-length', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "string-to-codepoints"},
       {xqSeqType, 'xs:integer', zero_or_many}, [],
       {xqerl_fn, 'string-to-codepoints', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "subsequence"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, subsequence, 3}, 2,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, 'xs:double', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "subsequence"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, subsequence, 4}, 3,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, 'xs:double', one},
        {xqSeqType, 'xs:double', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "substring"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, substring, 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:double', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "substring"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, substring, 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:double', one},
        {xqSeqType, 'xs:double', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "substring-after"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'substring-after', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "substring-after"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'substring-after', 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "substring-before"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'substring-before', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "substring-before"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'substring-before', 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', zero_or_one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "sum"},
       {xqSeqType, 'xs:anyAtomicType', one}, [], {xqerl_fn, sum, 2}, 1,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "sum"},
       {xqSeqType, 'xs:anyAtomicType', zero_or_one}, [], {xqerl_fn, sum, 3}, 2,
       [{xqSeqType, 'xs:anyAtomicType', zero_or_many},
        {xqSeqType, 'xs:anyAtomicType', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "tail"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, tail, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "timezone-from-date"},
       {xqSeqType, 'xs:dayTimeDuration', zero_or_one}, [],
       {xqerl_fn, 'timezone-from-date', 2}, 1, [{xqSeqType, 'xs:date', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "timezone-from-dateTime"},
       {xqSeqType, 'xs:dayTimeDuration', zero_or_one}, [],
       {xqerl_fn, 'timezone-from-dateTime', 2}, 1,
       [{xqSeqType, 'xs:dateTime', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "timezone-from-time"},
       {xqSeqType, 'xs:dayTimeDuration', zero_or_one}, [],
       {xqerl_fn, 'timezone-from-time', 2}, 1, [{xqSeqType, 'xs:time', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "tokenize"},
       {xqSeqType, 'xs:string', zero_or_many}, [], {xqerl_fn, tokenize, 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "tokenize"},
       {xqSeqType, 'xs:string', zero_or_many}, [], {xqerl_fn, tokenize, 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "tokenize"},
       {xqSeqType, 'xs:string', zero_or_many}, [], {xqerl_fn, tokenize, 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "trace"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, trace, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "trace"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, trace, 3}, 2,
       [{xqSeqType, item, zero_or_many}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "transform"},
       {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}, [],
       {xqerl_fn, transform, 2}, 1,
       [{xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "translate"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, translate, 4}, 3,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one},
        {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "true"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, true, 1}, 0, []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "unordered"},
       {xqSeqType, item, zero_or_many}, [], {xqerl_fn, unordered, 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "unparsed-text"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'unparsed-text', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "unparsed-text"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'unparsed-text', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "unparsed-text-available"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'unparsed-text-available', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn",
        "unparsed-text-available"},
       {xqSeqType, 'xs:boolean', one}, [], {xqerl_fn, 'unparsed-text-available', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "unparsed-text-lines"},
       {xqSeqType, 'xs:string', zero_or_many}, [],
       {xqerl_fn, 'unparsed-text-lines', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "unparsed-text-lines"},
       {xqSeqType, 'xs:string', zero_or_many}, [],
       {xqerl_fn, 'unparsed-text-lines', 3}, 2,
       [{xqSeqType, 'xs:string', zero_or_one}, {xqSeqType, 'xs:string', one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "upper-case"},
       {xqSeqType, 'xs:string', one}, [], {xqerl_fn, 'upper-case', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "uri-collection"},
       {xqSeqType, 'xs:anyURI', zero_or_many}, [], {xqerl_fn, 'uri-collection', 1}, 0,
       []},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "uri-collection"},
       {xqSeqType, 'xs:anyURI', zero_or_many}, [], {xqerl_fn, 'uri-collection', 2}, 1,
       [{xqSeqType, 'xs:string', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "xml-to-json"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'xml-to-json', 2}, 1,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined},
         zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "xml-to-json"},
       {xqSeqType, 'xs:string', zero_or_one}, [], {xqerl_fn, 'xml-to-json', 3}, 2,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, zero_or_one},
        {xqSeqType, {xqFunTest, map, [], undefined, any, any}, one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "year-from-date"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, 'year-from-date', 2}, 1,
       [{xqSeqType, 'xs:date', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "year-from-dateTime"},
       {xqSeqType, 'xs:integer', zero_or_one}, [], {xqerl_fn, 'year-from-dateTime', 2},
       1, [{xqSeqType, 'xs:dateTime', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "years-from-duration"},
       {xqSeqType, 'xs:integer', zero_or_one}, [],
       {xqerl_fn, 'years-from-duration', 2}, 1,
       [{xqSeqType, 'xs:duration', zero_or_one}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "zero-or-one"},
       {xqSeqType, item, zero_or_one}, [], {xqerl_fn, 'zero-or-one', 2}, 1,
       [{xqSeqType, item, zero_or_many}]},
      {{qname, "http://www.w3.org/2005/xpath-functions", "fn", "put"},
       {xqSeqType, 'empty-sequence', one},
       [{annotation, {{qname, "http://www.w3.org/2012/xquery", [], "updating"}, []}}],
       {xqerl_fn, put, 3}, 2,
       [{xqSeqType, {xqKindTest, node, undefined, undefined, undefined}, one},
        {xqSeqType, 'xs:string', one}]}],
      namespaces =>
     [{xqNamespace, 'no-namespace', []},
      {xqNamespace, "http://www.w3.org/2005/xquery-local-functions", "local"},
      {xqNamespace, "http://www.w3.org/2005/xpath-functions", "fn"},
      {xqNamespace, "http://www.w3.org/2001/XMLSchema-instance", "xsi"},
      {xqNamespace, "http://www.w3.org/XML/1998/namespace", "xml"},
      {xqNamespace, "http://www.w3.org/2001/XMLSchema", "xs"},
      {xqNamespace, "http://www.w3.org/2005/xpath-functions/math", "math"},
      {xqNamespace, "http://www.w3.org/2005/xpath-functions/map", "map"},
      {xqNamespace, "http://www.w3.org/2005/xpath-functions/array", "array"},
      {xqNamespace, "http://www.w3.org/2005/xqt-errors", "err"},
      {xqNamespace, "http://www.xqsharp.com/raytracer", "raytracer"},
      {xqNamespace, "http://www.xqsharp.com/raytracer/scene", "scene"}]}.


%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 


main(Options) ->
    Ctx0 = xqerl_context:merge(init(), Options),
    Ctx = begin
       Local__2 = maps:get(context_item, Options, []),
       xqerl_context:set_context_item(Ctx0, Local__2, 1,
                  {xqAtomicValue, 'xs:integer', xqerl_seq3:size(Local__2)})
     end,
    begin
      Query = xqerl_seq3:val_map(
                fun(Local__1) when erlang:is_map(Local__1) ->
                       xqerl_operators:lookup(Ctx, Local__1, {xqAtomicValue, 'xs:string', "arg"});
                   ([Local__1]) when erlang:is_map(Local__1) ->
                      xqerl_operators:lookup(Ctx, Local__1, {xqAtomicValue, 'xs:string', "arg"});
                   ({array, _} = Local__1) ->
                      xqerl_operators:lookup(Ctx, Local__1, {xqAtomicValue, 'xs:string', "arg"});
                   (Ctx__1) ->
                      Local__1 = xqerl_types:value(xqerl_fn:'function-lookup'(Ctx,
                                     xqerl_fn:'QName'(Ctx,
                                            {xqAtomicValue,
                                             'xs:string',
                                             "http://www.w3.org/2005/xquery-local-functions"},
                                            {xqAtomicValue,
                                             'xs:string', "missing"}),
                                     {xqAtomicValue, 'xs:integer', 1})),
                if erlang:is_function(Local__1) ->
                  case Local__1 == fun xqerl_fn:concat/2 of
                    true ->
                        Local__1(Ctx, xqerl_seq3:flatten([{xqAtomicValue, 'xs:string', "arg"}]));
                    _ -> Local__1(Ctx, {xqAtomicValue, 'xs:string', "arg"})
                  end;
                   true ->
                     xqerl_operators:lookup(Ctx, Local__1, {xqAtomicValue, 'xs:string', "arg"})
                end
             end,
             xqerl_fn:'function-lookup'(Ctx,
                         xqerl_fn:'QName'(Ctx,
                                {xqAtomicValue, 'xs:string',
                                 "http://www.w3.org/2005/xquery-local-functions"},
                                {xqAtomicValue, 'xs:string', "missing"}),
                         {xqAtomicValue, 'xs:integer', 1})),
      xqerl_types:return_value(Query)
    end.