# Run on 
# - any pull request
# - any 'feature' branch except main
# tasks: 
# build production tar 
#  - build_check:  builds tar in erlang:alpine container
#  - xqerl_slim:   builds tar in erlang:slim container
#  - container_image:  on ubuntu-latest pulls erlang:alpine to build tar 

name: checks on running xqerl instance
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches-ignore:
      - main
jobs:
  build_check:
    uses: ./.github/workflows/build-check.yml
  xqerl_slim:
    needs: build_check
    uses: ./.github/workflows/xqerl-slim-tar.yml
  container-image:
    #needs: build_check
    uses: ./.github/workflows/xqerl-alpine-image.yml
